database_url: 'postgres://localhost/cliche'

# http://docs.celeryproject.org/en/latest/configuration.html
broker_url: 'redis://localhost/1'

CELERYBEAT_SCHEDULE:
  'tvtropes-sync':
    task: 'cliche.services.tvtropes.crawler.crawl'
    schedule: !!python/object/apply:datetime.timedelta [1, 0, 0]
  'wikipedia-sync':
    task: 'cliche.services.wikipedia.crawler.crawl'
    schedule: !!python/object/apply:datetime.timedelta [1, 0, 0]

CELERY_TIMEZONE: 'UTC'
